### ISSUE TITLE
Research: Pick up one service that can import 3d NFT

### ISSUE THREAD

**Issue by taijusanagi** [HackerSamuraiDAO/2022-Polygon-BUIDL-IT-submission#14]
This is research for picking up one service that can import 3d NFT

**Comment by taijusanagi** [comment]
I can think of 'cryptovoxel', but I'm not sure it accepts 3d NFT import.

**Comment by yama-o** [comment]
Cluster" can contain 3D models, but does not accept NFT.

**Comment by taijusanagi** [comment]
Let's use this service.

<img width="1070" alt="Screen Shot 2022-08-22 at 22 44 51" src="https://user-images.githubusercontent.com/38043569/185936042-835ba012-5757-4b9b-b7af-e30713afef9b.png">
