### ISSUE TITLE
Prepare logo and key visual for this service

### ISSUE THREAD

**Issue by taijusanagi** [HackerSamuraiDAO/2022-Polygon-BUIDL-IT-submission#20]
Prepare logo and key visual of Rakugaki

**Comment by yama-o** [comment]
![RAKUGAKI_penki_only](https://user-images.githubusercontent.com/69063610/185757736-2b1e885e-b752-4438-807f-ac454eb85e97.gif)

**Comment by taijusanagi** [comment]
this is done by extracting image from gif
